// <auto-generated />
using System;
using MeetManagerWPF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetManagerWPF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714110747_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetManagerWPF.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("RoomID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Koncert"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Oslava"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Divadlo"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ples"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vystoupení"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sraz"
                        });
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "AdminRoleId-51sa9-sdd18",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "ManagerRoleId-21ga5-sda13",
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = "UserRoleId-54sa9-sda87",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Capacity = 120,
                            Location = "Vysočina",
                            Name = "chata pod smrkem"
                        },
                        new
                        {
                            ID = 2,
                            Capacity = 120,
                            Location = "Brno",
                            Name = "jeskyně"
                        },
                        new
                        {
                            ID = 3,
                            Capacity = 120,
                            Location = "Lipník",
                            Name = "sokolovna"
                        },
                        new
                        {
                            ID = 4,
                            Capacity = 120,
                            Location = "Pardubice",
                            Name = "areal u smutného psa"
                        });
                });

            modelBuilder.Entity("MeetManagerWPF.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Juzba@gmail.com",
                            Name = "Juzba",
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=1$+g3wENe8VfgrJvTd4E9YNQ$zvtCx0lwFdXwvR6DLKTOH6FJzm8rB6y54wSEpXbIkJk",
                            RoleId = "AdminRoleId-51sa9-sdd18"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Katka@gmail.com",
                            Name = "Katka",
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=1$VSs65qBpJTKEJSTb7qXkAw$fBlpCgya4Z9LRmKnhUFzXh7tqnXrWSl2vyHkNCwEKCg",
                            RoleId = "ManagerRoleId-21ga5-sda13"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Karel@gmail.com",
                            Name = "Karel",
                            PasswordHash = "$argon2id$v=19$m=65536,t=3,p=1$tyqbuA8MlWrR6ZE7pWMioA$wjo5b2y+qFdDrbr23ymFvKi9xv2W55g1uvX/3T0z9/s",
                            RoleId = "UserRoleId-54sa9-sda87"
                        });
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Event", b =>
                {
                    b.HasOne("MeetManagerWPF.Model.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetManagerWPF.Model.Room", "Room")
                        .WithMany("Events")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Invitation", b =>
                {
                    b.HasOne("MeetManagerWPF.Model.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeetManagerWPF.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.User", b =>
                {
                    b.HasOne("MeetManagerWPF.Model.Invitation", null)
                        .WithMany("Participants")
                        .HasForeignKey("InvitationId");

                    b.HasOne("MeetManagerWPF.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Invitation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Room", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
