// <auto-generated />
using MeetManagerWPF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeetManagerWPF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704174802_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeetManagerWPF.Model.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = "AdminRoleId-51sa9-sdd18",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = "ManagerRoleId-21ga5-sda13",
                            RoleName = "Manager"
                        },
                        new
                        {
                            Id = "UserRoleId-54sa9-sda87",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("MeetManagerWPF.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Juzba",
                            Password = "123456",
                            RoleId = "AdminRoleId-51sa9-sdd18"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Katka",
                            Password = "123456",
                            RoleId = "ManagerRoleId-21ga5-sda13"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Karel",
                            Password = "123456",
                            RoleId = "UserRoleId-54sa9-sda87"
                        });
                });

            modelBuilder.Entity("MeetManagerWPF.Model.User", b =>
                {
                    b.HasOne("MeetManagerWPF.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MeetManagerWPF.Model.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
